### PR TITLE
Created new, more secure sound system

### PR DESCRIPTION
**Pull request by boynedmaster**
Solution for #1028.

You can test it out here: https://www.roblox.com/games/983306953/sound-test.

To use the new sound system, create an object (doesn't matter what type) in SoundService named UseNewSoundSystem.

Again, as I said in the original issue, this should *not* be pushed until Roblox creates a property for it (or if it is confirmed they won't). Having to create an object instead is a hacky method of doing so.

Not sure why the commits are showing up as being made by Unknown, I'm just going to assume I somehow screwed up my git commands.

### CODE REVIEW

**Comment by boynedmaster** [comment]
Not sure what that conflict is about, can anyone inform me?

**Comment by stillunt1tled** [comment]
@boynedmaster conflicts generally happen when another PR/change is pushed and this PR does not include that change. Can be solved by pulling the current commit to your fork. (in command-line you can type `git pull`)

**Comment by boynedmaster** [comment]
There, I believe I fixed it.

**Comment by hockeychaos** [comment]
unfortunately we only look for bug fixes in pull requests from the community. A full rewrite of a system or new features will not be accepted.

**Pull request closed without merging**
