### PR TITLE
Prevent infinite yield in FreeCamera

### PR DESCRIPTION
**Pull request by suufi**
Infinite yield possible so let's put a timeout. :stuck_out_tounge:

### CODE REVIEW

**Comment by Kampfkarren** [comment]
This'll just make the script error if they don't exist in the 5 seconds. Why care about the infinite yield? Better than errors.

**Comment by suufi** [comment]
I mean why won't they exist?

**Comment by Kampfkarren** [comment]
Why worry about an infinite yield then?

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosen [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.

**Pull request closed without merging**
