### PR TITLE
[#1043] Deprecate lower camel case method names

### PR DESCRIPTION
**Pull request by ghost**
Resolves issue #1043 by renaming the methods to reflect the method names of BindableEvent.

`Signal:fire() -> Signal:Fire()`
`Signal:connect() -> Signal:Connect()`
`Signal:wait() -> Signal:Wait()`

The old methods *still* exist for compatibility, but are deprecated

### CODE REVIEW

**Comment by Kampfkarren** [comment]
You can clean up your code by instead of doing...

```
function sig:connect(f)
	self:Connect(f)
end
```

...just do

`sig.connect = sig.Connect`

**Comment by stillunt1tled** [comment]
@Kampfkarren People using the old API did `sig:connect()`, not `sig.connect()`, so this would not work.

**Comment by Kampfkarren** [comment]
@stillunt1tled `x:y(...)` is the exact same as `x.y(x, ...)`.

Thus, if you have this code

```
local X = {}

function X:A()
    print("hello")
end

X.B = X.A
```

Then attempting to call `X:B()` will do the exact same thing as `X:A()`. This is because `X:B()` will now be equivalent to `X.A(X.A)`.

My point is, `sig.connect = sig.Connect` is the exact same as what you're doing, just more efficient and readable.

**Comment by stillunt1tled** [comment]
@Kampfkarren while I will take your suggestion, if this is done, `self` will never be passed to the method (not that its used in this script, I just concerned about future implementations that use `self`)

**Comment by J0shhT** [comment]
@stillunt1tled The colon operator automatically passes self as a parameter to the function. That's the whole point of the colon operator in the first place.

https://www.lua.org/manual/5.1/manual.html#2.5.8

"A call v:name(args) is syntactic sugar for v.name(v,args), except that v is evaluated only once."

**Comment by stillunt1tled** [comment]
^ this is why I don't contribute to this repository.

Thats the point. If you dont have the `:` operator, self wont be passed. I'm saying if they use it in a future version of this script, all of the

**Comment by Kampfkarren** [comment]
Er, no. self is automatically passed.

https://repl.it/repls/IdealisticWebbedLogins

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosen [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.

**Pull request closed without merging**
