### PR TITLE
Removed unneeded warning message

### PR DESCRIPTION
**Pull request by JetCrusherTorpedo**
Fix issue #468

### CODE REVIEW

**Comment by JetCrusherTorpedo** [comment]
Note: using `math.huge` as the timeout does work. Open a new baseplate, type `print(Workspace:WaitForChild("Part",math.huge).Position)` in the command prompt. Wait as long as you like, then insert a part.

**Comment by hockeychaos** [comment]
for consistency can you use the 24 hour wait convention? instead of math.huge?

**Comment by JetCrusherTorpedo** [comment]
@hockeychaos Done

**Comment by SolarCrane** [comment]
This feels like we are just running around the issue:
We implemented the potential infinite yield detection feature to identify possible bugs, so to say wait almost forever undermines what we set out to do.
Therefore, I think it would be better to hook this into a .ChildAdded event style and let the script fully execute.

**Comment by JetCrusherTorpedo** [comment]
@SolarCrane How's that?

**Comment by SolarCrane** [comment]
These updates seem a bit drastic, I think we should just rollback a couple commits to what @hockeychaos  recommended.

**Comment by JetCrusherTorpedo** [comment]
@SolarCrane OK, done.

**Comment by JetCrusherTorpedo** [comment]
@SolarCrane @hockeychaos Can this be merged?

**Pull request merged**
