### PR TITLE
VR-133 Make panel positioning work with HeadScale

### PR DESCRIPTION
**Pull request by kyle-emmerich**

### CODE REVIEW

**Comment by BinaryResolved** [comment]
What happened?

**Comment by kyle-emmerich** [comment]
Found a little bug, I'm gonna reopen it once I fix that.

**Comment by BinaryResolved** [comment]
Ah, makes sense.

-----Original Message-----

**Comment by BinaryResolved** [comment]
lol we all make mistakes. I would be worried if you didn't.

**Pull request closed without merging**
