### PR TITLE
Attempt to fix issue: 293

### PR DESCRIPTION
**Pull request by BinaryResolved**
Attempt to fix issue: 293.

### CODE REVIEW

**Comment by TheSneak** [comment]
This seems more appropriate to me:

    if frame:FindFirstChild("Icon") then
    	frame.Icon.Image = 'http://www.roblox.com/Thumbs/Avatar.ashx?x=100&y=100&userId='..math.max(1, player.userId)
    end
    if frame:FindFirstChild("NameLabel") then
    	frame.NameLabel.Text = player.Name
    end
    frame.ImageTransparency = frameDefaultTransparency

But a better fix would address the question "Why does Icon sometimes not exist as a child?"

**Comment by BinaryResolved** [comment]
What if then 'NameLabel' is a valid member of frame but 'Icon' is not. Then it would show the name and not the Picture. Actually what if we did
`if frame:FindFirstChild("Icon") and frame:FindFirstChild("NameLabel") then
     frame.Icon.Image = 'http://www.roblox.com/Thumbs/Avatar.ashx?x=100&y=100&userId='..math.max(1, player.userId)
frame.NameLabel.Text = player.Name
`
What do you think of that?

**Comment by hockeychaos** [comment]
I'm not sure if this will actually fix anything, so for now I'm going to close this.

**Comment by BinaryResolved** [comment]
Well, the attempt was thrown detect if it was the child. If so then continue, if not then stop and will not error out the script.

**Comment by BinaryResolved** [comment]
*to

**Pull request closed without merging**
