### PR TITLE
Change Clamp to math.clamp

### PR DESCRIPTION
**Pull request by Kampfkarren**

### CODE REVIEW

**Comment by PhoenixShay** [comment]
Not sure why this is needed. Probably a reason why they are using a custom function.

**Comment by JanBerktold** [comment]
That code has likely been written before the addition of math.clamp to ROBLOX lua. Less code to maintain is usually better.

**Comment by kyle-emmerich** [comment]
Yeah, this code just predates me adding math.clamp. Unfortunately, the function signatures don't match. You'll want to rearrange them. The old Clamp function here takes min, max, x, but the math.clamp function takes x, min, max.

**Comment by boynedmaster** [comment]
You're right. I'll fix that when I'm at a computer and I remember.

**Comment by boynedmaster** [comment]
There, that should fix it.

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosen [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.

**Pull request closed without merging**
