### PR TITLE
RobloxGui/Modules variable usage

### PR DESCRIPTION
**Pull request by Wittiest**
A few times CoreGui.RobloxGui was used when RobloxGui was already initialized.

TopbarConstants had an incorrect comment title.

### CODE REVIEW

**Comment by stillunt1tled** [comment]
This PR has conflicts, please resolve them.

Also, some CoreScripts use `CoreGui.RobloxGui.Modules` or `RobloxGui.Modules` when `Modules` is already defined and initalized. I do think you should fix this too.

Thanks for helping out :+1:

**Comment by Wittiest** [comment]
Done.

**Comment by hockeychaos** [comment]
Looks like there are conflicts, will close for now but can look at if these issues still persist

**Comment by Wittiest** [comment]
I could have fixed the conflicts. Though, I'm sure this sort of PR isn't vital to your code so unless requested I will not resubmit it

**Pull request closed without merging**
